server:
  port: 9091
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/money-workflow
    username: root
    password: gopal
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true